<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [1]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [11]:
#Your code for part A of Exercise 1 goes here
a=np.random.randint(3,12,size=(5,7))
a.dtype

dtype('int32')

In [13]:
#Your code for part B of Exercise 1 goes here
a.max()

11

In [18]:
#Your code for part C of Exercise 1 goes here
a.min(axis=1)

array([4, 3, 5, 3, 3])

In [20]:
#Your code for part D of Exercise 1 goes here
a.argmin(axis=1)

array([6, 2, 2, 1, 1], dtype=int64)

<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [24]:
#Your code for Exercise 2 goes here
b=np.arange(4,100,5)
b

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [26]:
#Your code for Exercise 3 goes here
c=b.reshape(4,5)
c

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [29]:
#Your code for Exercise 4 goes here
d=np.random.randn(4,2,3)
d

array([[[ 0.73332673, -0.23294652, -0.14545658],
        [-0.22453278, -0.64228256,  0.29258924]],

       [[-0.74879402, -0.02867211, -1.44733175],
        [-1.0742393 ,  0.77015597, -0.267417  ]],

       [[-0.07139523,  1.16454721, -0.97130865],
        [-1.32455765,  0.02283337,  0.43414064]],

       [[ 0.29742327, -0.00637581, -1.08208143],
        [ 0.13282611,  0.73913683,  1.71944643]]])

<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [34]:
#Your code for Exercise 5 goes here
e=np.eye(6,k=-2,dtype=int)
e

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [38]:
#Your code for part A of Exercise 6 goes here
f=np.arange(3,34,2)
g=f[-4:]
g

array([27, 29, 31, 33])

In [41]:
#Your code for part B of Exercise 6 goes here
h=f[f%3==0]
h

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [46]:
#Your code for part A of Exercise 7 goes here
i=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
i[4,5]

72

In [49]:
#Your code for part B of Exercise 7 goes here
i[2:,3:5]

array([[76,  3],
       [26, 71],
       [38, 54]])

In [50]:
i[1:,:]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7],
       [75, 17, 17, 38, 54, 72, 78]])

<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [56]:
#Your code for part A of Exercise 8 goes here
j=np.arange(1,50,3)
k=j[(j>7)&(j<43)]
k

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [61]:
#Your code for part B of Exercise 8 goes here
l=k[k%2==0]
l

array([10, 16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [107]:
#Your code for part A of Exercise 9 goes here
m=np.random.randn(20)
m.mean()


0.012626356952888445

In [116]:
m

array([ 0.81860553,  2.35850244, -0.16679005, -0.357207  ,  0.24535355,
       -2.92900692, -0.52864945,  0.7128013 , -0.17821578,  0.62794514,
        1.74642877, -0.53997737,  0.50517153,  0.68974648,  0.34018275,
       -0.22952599, -1.93207066,  0.01660338, -1.05643414,  0.10906362])

In [108]:
#Your code for part B of Exercise 9 goes here
m.std()

1.1256076693381667

In [109]:
#Your code for part C of Exercise 9 goes here
np.median(m)

0.06283350107747633

In [131]:
#Your code for part D of Exercise 9 goes here
absv=np.abs(m)
Log=np.log10(absv)
np.mean(Log)

-0.32403705945020145

<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [159]:
#Your code for part A of Exercise 10 goes here
input=np.array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

def switchit(inp):
    i=inp.astype(float)
    return [ele for ele in reversed(i)]

switchit(input)

[23.0, 21.0, 19.0, 17.0, 15.0, 13.0, 11.0, 9.0, 7.0, 5.0, 3.0, 1.0]

In [165]:
#Your code for part B of Exercise 10 goes here
def FLAT(x):
    y= x.flatten()
    return y

In [166]:
insert=np.array([[7, 4, 8, 3],[6, 3, 4, 3],[4, 7, 5, 4]])

In [167]:
FLAT(insert)

array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])